### ISSUE TITLE
Error while converting to keras model

### ISSUE THREAD

**Issue by vihari1729** [Ma-Dan/keras-yolo4#25]
I have trained yolo.weights (with my custom dataset having 3 classes) and the detections are coming fine while testing with that model. But when i am converting it to keras model, I am getting below error
```
File "convert.py", line 172, in <module>
    yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path)
  File "convert.py", line 157, in __init__
    self.load_yolo()
  File "convert.py", line 98, in load_yolo
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

```
Could someone tell me why it is happening and what changes I should make

**Comment by elesun2018** [comment]
same problem

**Comment by farhantandia** [comment]
same problem with custom dataset

**Comment by Melkeydev** [comment]
@elesun2018 @farhantandia any updates? I am also on this issue with the original yolov4.weights downloaded/

**Comment by farhantandia** [comment]
the model is successfully converted, I forgot to specify the classes.txt if you are using custom dataset.

**Comment by Melkeydev** [comment]
@farhantandia I am using the stock yolov4.weight files?
When I run the convert.py, I am getting the buffer issue size. How did you resolve?

**Comment by farhantandia** [comment]
It also works for standard yolov4 weights in my case.

**Comment by Melkeydev** [comment]
@farhantandia can you share your code?
the convert.py - specifically? Still not working for me haha

**Comment by xellDart** [comment]
same problem, any solution?

**Comment by farhantandia** [comment]
[convert.zip](https://github.com/Ma-Dan/keras-yolo4/files/5066860/convert.zip)
@Amokstakov

**Comment by Shridharpawar77** [comment]
This convert file is also not working please provide working codes

**Comment by Ivan-basis** [comment]
@vihari1729 @xellDart which version of keras (and TF) do you use? I faced the same error due to another version of keras that has slightly different indexing mechanism of new created layers, i.e. in my case the first Conv2D layer had name "conv2d" (in keras 2.4.0) instead of expected "conv2d_1" (in keras 2.2.4). So, some layers become missed and weights are assigned by wrong names with shift to another layers. This leads to this error when it faces with another shape of some layer.

Try to use [these ](https://github.com/Ma-Dan/keras-yolo4/issues/14#issuecomment-631182234) versions

**Comment by benjamin2044** [comment]
In line 71(convert.py) change "conv2d_" to conv2D
if layer_name.startswith('conv2D'):

There will be warnings but the tensorflow model "yolo4_weight.h5" will be generated.
